name: main build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: Restore NuGet packages
        run: nuget restore SQLInjectionAnalyzer.sln
      - name: Build
        run: msbuild SQLInjectionAnalyzer.sln